use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ServiceType {
    FireStation,
    PoliceStation,
    Hospital,
    ElementarySchool,
    HighSchool,
    University,
    Library,
    SmallPark,
    LargePark,
    Playground,
    Plaza,
    SportsField,
    Stadium,
    Landfill,
    RecyclingCenter,
    Incinerator,
    Cemetery,
    Crematorium,
    CityHall,
    Museum,
    Cathedral,
    TVStation,
    BusDepot,
    TrainStation,
    // New multi-tier variants
    FireHouse,
    FireHQ,
    PoliceKiosk,
    PoliceHQ,
    Prison,
    MedicalClinic,
    MedicalCenter,
    Kindergarten,
    SubwayStation,
    TramDepot,
    FerryPier,
    SmallAirstrip,
    RegionalAirport,
    InternationalAirport,
    TransferStation,
    CellTower,
    DataCenter,
    HomelessShelter,
    WelfareOffice,
    PostOffice,
    MailSortingCenter,
    HeatingBoiler,
    DistrictHeatingPlant,
    GeothermalPlant,
    WaterTreatmentPlant,
    WellPump,
}

impl ServiceType {
    pub fn name(self) -> &'static str {
        match self {
            ServiceType::FireStation => "Fire Station",
            ServiceType::FireHouse => "Fire House",
            ServiceType::FireHQ => "Fire HQ",
            ServiceType::PoliceStation => "Police Station",
            ServiceType::PoliceKiosk => "Police Kiosk",
            ServiceType::PoliceHQ => "Police HQ",
            ServiceType::Prison => "Prison",
            ServiceType::Hospital => "Hospital",
            ServiceType::MedicalClinic => "Medical Clinic",
            ServiceType::MedicalCenter => "Medical Center",
            ServiceType::ElementarySchool => "Elementary School",
            ServiceType::HighSchool => "High School",
            ServiceType::University => "University",
            ServiceType::Library => "Library",
            ServiceType::Kindergarten => "Kindergarten",
            ServiceType::SmallPark => "Small Park",
            ServiceType::LargePark => "Large Park",
            ServiceType::Playground => "Playground",
            ServiceType::Plaza => "Plaza",
            ServiceType::SportsField => "Sports Field",
            ServiceType::Stadium => "Stadium",
            ServiceType::Landfill => "Landfill",
            ServiceType::RecyclingCenter => "Recycling Center",
            ServiceType::Incinerator => "Incinerator",
            ServiceType::TransferStation => "Transfer Station",
            ServiceType::Cemetery => "Cemetery",
            ServiceType::Crematorium => "Crematorium",
            ServiceType::CityHall => "City Hall",
            ServiceType::Museum => "Museum",
            ServiceType::Cathedral => "Cathedral",
            ServiceType::TVStation => "TV Station",
            ServiceType::BusDepot => "Bus Depot",
            ServiceType::TrainStation => "Train Station",
            ServiceType::SubwayStation => "Subway Station",
            ServiceType::TramDepot => "Tram Depot",
            ServiceType::FerryPier => "Ferry Pier",
            ServiceType::SmallAirstrip => "Small Airstrip",
            ServiceType::RegionalAirport => "Regional Airport",
            ServiceType::InternationalAirport => "International Airport",
            ServiceType::CellTower => "Cell Tower",
            ServiceType::DataCenter => "Data Center",
            ServiceType::HomelessShelter => "Homeless Shelter",
            ServiceType::WelfareOffice => "Welfare Office",
            ServiceType::PostOffice => "Post Office",
            ServiceType::MailSortingCenter => "Mail Sorting Center",
            ServiceType::WaterTreatmentPlant => "Water Treatment Plant",
            ServiceType::WellPump => "Well Pump",
            ServiceType::HeatingBoiler => "Heating Boiler",
            ServiceType::DistrictHeatingPlant => "District Heating Plant",
            ServiceType::GeothermalPlant => "Geothermal Heating Plant",
        }
    }
}
