//! Tool categories for infrastructure: Roads, Zones, Utilities, Emergency,
//! Education, and Parks.

use rendering::input::ActiveTool;

use super::{ToolCategory, ToolItem};

/// Returns tool categories for core infrastructure placement.
pub(super) fn infrastructure_categories() -> Vec<ToolCategory> {
    vec![
        ToolCategory {
            icon: "R",
            name: "Roads",
            items: vec![
                ToolItem {
                    tool: Some(ActiveTool::Road),
                    icon: "=",
                    name: "Local Road",
                    cost: Some(10.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::RoadAvenue),
                    icon: "==",
                    name: "Avenue",
                    cost: Some(20.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::RoadBoulevard),
                    icon: "===",
                    name: "Boulevard",
                    cost: Some(30.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::RoadHighway),
                    icon: "HW",
                    name: "Highway",
                    cost: Some(40.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::RoadOneWay),
                    icon: "->",
                    name: "One-Way",
                    cost: Some(15.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::RoadPath),
                    icon: "..",
                    name: "Path",
                    cost: Some(5.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::RoadUpgrade),
                    icon: "Up",
                    name: "Upgrade",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::AutoGrid),
                    icon: "##",
                    name: "Auto-Grid",
                    cost: None,
                    overlay: None,
                },
            ],
        },
        ToolCategory {
            icon: "Z",
            name: "Zones",
            items: vec![
                ToolItem {
                    tool: Some(ActiveTool::ZoneResidentialLow),
                    icon: "RL",
                    name: "Res Low",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::ZoneResidentialMedium),
                    icon: "RM",
                    name: "Res Medium",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::ZoneResidentialHigh),
                    icon: "RH",
                    name: "Res High",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::ZoneCommercialLow),
                    icon: "CL",
                    name: "Com Low",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::ZoneCommercialHigh),
                    icon: "CH",
                    name: "Com High",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::ZoneIndustrial),
                    icon: "I",
                    name: "Industrial",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::ZoneOffice),
                    icon: "O",
                    name: "Office",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::ZoneMixedUse),
                    icon: "MU",
                    name: "Mixed-Use",
                    cost: None,
                    overlay: None,
                },
            ],
        },
        ToolCategory {
            icon: "U",
            name: "Utilities",
            items: vec![
                ToolItem {
                    tool: Some(ActiveTool::PlacePowerPlant),
                    icon: "PP",
                    name: "Power Plant",
                    cost: Some(800.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceSolarFarm),
                    icon: "SF",
                    name: "Solar Farm",
                    cost: Some(1200.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceWindTurbine),
                    icon: "Wi",
                    name: "Wind Turbine",
                    cost: Some(600.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceNuclearPlant),
                    icon: "NP",
                    name: "Nuclear Plant",
                    cost: Some(5000.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceGeothermal),
                    icon: "GT",
                    name: "Geothermal",
                    cost: Some(3000.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceWaterTower),
                    icon: "WA",
                    name: "Water Tower",
                    cost: Some(600.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceSewagePlant),
                    icon: "SP",
                    name: "Sewage Plant",
                    cost: Some(500.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlacePumpingStation),
                    icon: "PS",
                    name: "Pumping Station",
                    cost: Some(400.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceWaterTreatment),
                    icon: "WP",
                    name: "Water Treatment",
                    cost: Some(1000.0),
                    overlay: None,
                },
            ],
        },
        ToolCategory {
            icon: "E",
            name: "Emergency",
            items: vec![
                ToolItem {
                    tool: Some(ActiveTool::PlaceFireHouse),
                    icon: "Fh",
                    name: "Fire House",
                    cost: Some(200.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceFireStation),
                    icon: "Fi",
                    name: "Fire Station",
                    cost: Some(500.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceFireHQ),
                    icon: "FQ",
                    name: "Fire HQ",
                    cost: Some(1500.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlacePoliceKiosk),
                    icon: "Pk",
                    name: "Police Kiosk",
                    cost: Some(200.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlacePoliceStation),
                    icon: "Po",
                    name: "Police Station",
                    cost: Some(500.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlacePoliceHQ),
                    icon: "PQ",
                    name: "Police HQ",
                    cost: Some(1500.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlacePrison),
                    icon: "Pr",
                    name: "Prison",
                    cost: Some(2000.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceMedicalClinic),
                    icon: "Mc",
                    name: "Medical Clinic",
                    cost: Some(300.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceHospital),
                    icon: "Ho",
                    name: "Hospital",
                    cost: Some(1000.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceMedicalCenter),
                    icon: "MC",
                    name: "Medical Center",
                    cost: Some(3000.0),
                    overlay: None,
                },
            ],
        },
        ToolCategory {
            icon: "S",
            name: "Education",
            items: vec![
                ToolItem {
                    tool: Some(ActiveTool::PlaceKindergarten),
                    icon: "Kg",
                    name: "Kindergarten",
                    cost: Some(400.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceElementarySchool),
                    icon: "El",
                    name: "Elementary",
                    cost: Some(750.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceHighSchool),
                    icon: "HS",
                    name: "High School",
                    cost: Some(1000.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceUniversity),
                    icon: "Un",
                    name: "University",
                    cost: Some(2000.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceLibrary),
                    icon: "Li",
                    name: "Library",
                    cost: Some(500.0),
                    overlay: None,
                },
            ],
        },
        ToolCategory {
            icon: "P",
            name: "Parks",
            items: vec![
                ToolItem {
                    tool: Some(ActiveTool::PlaceSmallPark),
                    icon: "SP",
                    name: "Small Park",
                    cost: Some(100.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceLargePark),
                    icon: "LP",
                    name: "Large Park",
                    cost: Some(300.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlacePlayground),
                    icon: "Pg",
                    name: "Playground",
                    cost: Some(200.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlacePlaza),
                    icon: "Pz",
                    name: "Plaza",
                    cost: Some(150.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceSportsField),
                    icon: "Sf",
                    name: "Sports Field",
                    cost: Some(400.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceStadium),
                    icon: "St",
                    name: "Stadium",
                    cost: Some(2000.0),
                    overlay: None,
                },
            ],
        },
    ]
}
