//! Tool categories for city services and overlays: Landmarks, Sanitation,
//! Transport, Telecom, Views, Environment, Terrain, Districts, and Tools.

use rendering::input::ActiveTool;
use rendering::overlay::OverlayMode;

use super::{ToolCategory, ToolItem};

/// Returns tool categories for services, overlays, and misc tools.
pub(super) fn services_categories() -> Vec<ToolCategory> {
    vec![
        ToolCategory {
            icon: "L",
            name: "Landmarks",
            items: vec![
                ToolItem {
                    tool: Some(ActiveTool::PlaceCityHall),
                    icon: "CH",
                    name: "City Hall",
                    cost: Some(5000.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceMuseum),
                    icon: "Mu",
                    name: "Museum",
                    cost: Some(3000.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceCathedral),
                    icon: "Ca",
                    name: "Cathedral",
                    cost: Some(4000.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceTVStation),
                    icon: "TV",
                    name: "TV Station",
                    cost: Some(3500.0),
                    overlay: None,
                },
            ],
        },
        ToolCategory {
            icon: "G",
            name: "Sanitation",
            items: vec![
                ToolItem {
                    tool: Some(ActiveTool::PlaceLandfill),
                    icon: "Lf",
                    name: "Landfill",
                    cost: Some(300.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceRecyclingCenter),
                    icon: "RC",
                    name: "Recycling Center",
                    cost: Some(800.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceIncinerator),
                    icon: "In",
                    name: "Incinerator",
                    cost: Some(1500.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceTransferStation),
                    icon: "TS",
                    name: "Transfer Station",
                    cost: Some(500.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceCemetery),
                    icon: "Ce",
                    name: "Cemetery",
                    cost: Some(400.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceCrematorium),
                    icon: "Cr",
                    name: "Crematorium",
                    cost: Some(600.0),
                    overlay: None,
                },
            ],
        },
        ToolCategory {
            icon: "Tr",
            name: "Transport",
            items: vec![
                ToolItem {
                    tool: Some(ActiveTool::PlaceBusDepot),
                    icon: "BD",
                    name: "Bus Depot",
                    cost: Some(1000.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceTrainStation),
                    icon: "TS",
                    name: "Train Station",
                    cost: Some(2000.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceSubwayStation),
                    icon: "SS",
                    name: "Subway",
                    cost: Some(3000.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceTramDepot),
                    icon: "TD",
                    name: "Tram Depot",
                    cost: Some(1500.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceFerryPier),
                    icon: "FP",
                    name: "Ferry Pier",
                    cost: Some(800.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceSmallAirstrip),
                    icon: "SA",
                    name: "Small Airstrip",
                    cost: Some(5000.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceRegionalAirport),
                    icon: "RA",
                    name: "Regional Airport",
                    cost: Some(10000.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceInternationalAirport),
                    icon: "IA",
                    name: "Int'l Airport",
                    cost: Some(15000.0),
                    overlay: None,
                },
            ],
        },
        ToolCategory {
            icon: "TC",
            name: "Telecom",
            items: vec![
                ToolItem {
                    tool: Some(ActiveTool::PlaceCellTower),
                    icon: "CT",
                    name: "Cell Tower",
                    cost: Some(300.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::PlaceDataCenter),
                    icon: "DC",
                    name: "Data Center",
                    cost: Some(2000.0),
                    overlay: None,
                },
            ],
        },
        ToolCategory {
            icon: "V",
            name: "Views",
            items: vec![
                ToolItem {
                    tool: None,
                    icon: "Pw",
                    name: "Power",
                    cost: None,
                    overlay: Some(OverlayMode::Power),
                },
                ToolItem {
                    tool: None,
                    icon: "Wa",
                    name: "Water",
                    cost: None,
                    overlay: Some(OverlayMode::Water),
                },
                ToolItem {
                    tool: None,
                    icon: "Tr",
                    name: "Traffic",
                    cost: None,
                    overlay: Some(OverlayMode::Traffic),
                },
                ToolItem {
                    tool: None,
                    icon: "Po",
                    name: "Pollution",
                    cost: None,
                    overlay: Some(OverlayMode::Pollution),
                },
                ToolItem {
                    tool: None,
                    icon: "LV",
                    name: "Land Value",
                    cost: None,
                    overlay: Some(OverlayMode::LandValue),
                },
                ToolItem {
                    tool: None,
                    icon: "Ed",
                    name: "Education",
                    cost: None,
                    overlay: Some(OverlayMode::Education),
                },
                ToolItem {
                    tool: None,
                    icon: "Gb",
                    name: "Garbage",
                    cost: None,
                    overlay: Some(OverlayMode::Garbage),
                },
                ToolItem {
                    tool: None,
                    icon: "No",
                    name: "Noise",
                    cost: None,
                    overlay: Some(OverlayMode::Noise),
                },
                ToolItem {
                    tool: None,
                    icon: "WP",
                    name: "Water Pollution",
                    cost: None,
                    overlay: Some(OverlayMode::WaterPollution),
                },
                ToolItem {
                    tool: None,
                    icon: "GL",
                    name: "GW Level",
                    cost: None,
                    overlay: Some(OverlayMode::GroundwaterLevel),
                },
                ToolItem {
                    tool: None,
                    icon: "GQ",
                    name: "GW Quality",
                    cost: None,
                    overlay: Some(OverlayMode::GroundwaterQuality),
                },
            ],
        },
        ToolCategory {
            icon: "Ev",
            name: "Environment",
            items: vec![
                ToolItem {
                    tool: Some(ActiveTool::TreePlant),
                    icon: "Tp",
                    name: "Plant Tree",
                    cost: Some(50.0),
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::TreeRemove),
                    icon: "Tr",
                    name: "Remove Tree",
                    cost: None,
                    overlay: None,
                },
            ],
        },
        ToolCategory {
            icon: "Te",
            name: "Terrain",
            items: vec![
                ToolItem {
                    tool: Some(ActiveTool::TerrainRaise),
                    icon: "/\\",
                    name: "Raise",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::TerrainLower),
                    icon: "\\/",
                    name: "Lower",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::TerrainLevel),
                    icon: "--",
                    name: "Flatten",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::TerrainWater),
                    icon: "~~",
                    name: "Water",
                    cost: None,
                    overlay: None,
                },
            ],
        },
        ToolCategory {
            icon: "D",
            name: "Districts",
            items: vec![
                ToolItem {
                    tool: Some(ActiveTool::DistrictPaint(0)),
                    icon: "D0",
                    name: "Downtown",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::DistrictPaint(1)),
                    icon: "D1",
                    name: "Suburbs",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::DistrictPaint(2)),
                    icon: "D2",
                    name: "Industrial",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::DistrictPaint(3)),
                    icon: "D3",
                    name: "Waterfront",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::DistrictPaint(4)),
                    icon: "D4",
                    name: "Historic",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::DistrictPaint(5)),
                    icon: "D5",
                    name: "University",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::DistrictPaint(6)),
                    icon: "D6",
                    name: "Arts",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::DistrictPaint(7)),
                    icon: "D7",
                    name: "Tech Park",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::DistrictErase),
                    icon: "DE",
                    name: "Erase District",
                    cost: None,
                    overlay: None,
                },
            ],
        },
        ToolCategory {
            icon: "T",
            name: "Tools",
            items: vec![
                ToolItem {
                    tool: Some(ActiveTool::Bulldoze),
                    icon: "Bd",
                    name: "Bulldoze",
                    cost: None,
                    overlay: None,
                },
                ToolItem {
                    tool: Some(ActiveTool::Inspect),
                    icon: "?",
                    name: "Inspect",
                    cost: None,
                    overlay: None,
                },
            ],
        },
    ]
}
